# Generated by Django 2.0.6 on 2019-05-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=40)),
                ('series_name', models.CharField(max_length=80)),
                ('writer', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=80)),
                ('press_time', models.CharField(max_length=40)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ddprice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('press_count', models.CharField(max_length=20)),
                ('print_count', models.CharField(max_length=20)),
                ('inter_num', models.CharField(max_length=20)),
                ('b_class', models.CharField(max_length=20)),
                ('word_num', models.CharField(max_length=20)),
                ('page_num', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=20)),
                ('pack', models.CharField(max_length=20)),
                ('pub_time', models.DateTimeField()),
                ('sales', models.CharField(max_length=20)),
                ('pics', models.ImageField(blank=True, null=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('first', models.IntegerField(null=True)),
                ('second', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=40)),
                ('order_time', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField()),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.Book')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='b_classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.Class'),
        ),
        migrations.AddField(
            model_name='address',
            name='book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelapp.Book'),
        ),
        migrations.AddField(
            model_name='address',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.User'),
        ),
    ]
