# Generated by Django 2.0.6 on 2019-05-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_auto_20190516_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='print_count',
            field=models.IntegerField(),
        ),
    ]
