# Generated by Django 2.0.6 on 2019-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_auto_20190516_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discuss_count',
            field=models.IntegerField(null=True),
        ),
    ]
