# Generated by Django 2.0.6 on 2019-05-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_book_discuss_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_time',
            field=models.DateField(),
        ),
    ]
