# Generated by Django 2.0.6 on 2019-05-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0006_book_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='book_id',
        ),
    ]
