# Generated by Django 2.0.6 on 2019-05-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0008_auto_20190526_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='goods_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
